### ISSUE TITLE
TypeError: Cannot read property 'writable' of undefined   

### ISSUE THREAD

**Issue by adplaygit** [FreedomPrevails/JSMTProxy#16]
node version 8.9.3

i have error in this part of code
```

 if (!socket.server_socket.writable) {
                            socket.server_socket.destroy();
                        }

```
```
if (!socket.server_socket.writable) {
                                                  ^

TypeError: Cannot read property 'writable' of undefined
    at Socket.<anonymous> (\mtproxy.js:243:51)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
C:\nodemt\node_modules\starter\mtproxy.js:243
```

**Comment by shomo89** [comment]
I have the exact same problem after a year of it working properly. Do you have a solution yet?
