### ISSUE TITLE
How Can Fix This Errors?

### ISSUE THREAD

**Issue by HavijTeam** [FreedomPrevails/JSMTProxy#19]
I Receive To Many Of This Errors In My MTProxy Server:
`TypeError: Cannot read property 'writable' of undefined
    at Socket.<anonymous> (C:\JSMTProxy\mtproxy.js:223:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
TypeError: Cannot read property 'writable' of undefined
    at Socket.<anonymous> (C:\JSMTProxy\mtproxy.js:223:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
TypeError: Cannot read property 'writable' of undefined
    at Socket.<anonymous> (C:\JSMTProxy\mtproxy.js:223:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
TypeError: Cannot read property 'writable' of undefined
    at Socket.<anonymous> (C:\JSMTProxy\mtproxy.js:223:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
TypeError: Cannot read property 'writable' of undefined
    at Socket.<anonymous> (C:\JSMTProxy\mtproxy.js:223:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
TypeError: Cannot read property 'writable' of undefined
    at Socket.<anonymous> (C:\JSMTProxy\mtproxy.js:223:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
TypeError: Cannot read property 'writable' of undefined
    at Socket.<anonymous> (C:\JSMTProxy\mtproxy.js:223:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
TypeError: Cannot read property 'writable' of undefined
    at Socket.<anonymous> (C:\JSMTProxy\mtproxy.js:223:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
TypeError: Cannot read property 'writable' of undefined
    at Socket.<anonymous> (C:\JSMTProxy\mtproxy.js:223:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
`
I Attach My Server Status Image: 
![capture](https://user-images.githubusercontent.com/28505533/41200756-2f162696-6cc0-11e8-88b7-5882825f25af.PNG)
@FreedomPrevails

**Comment by BeInspired85** [comment]
The same issue on Ubuntu 22.04:

TypeError: Cannot read property 'writable' of undefined
    at Socket.<anonymous> (/home/pchelovod/JSMTProxy/mtproxy.js:223:32)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
