### ISSUE TITLE
JSM stopped working After the telegram servers were in trouble (Windows)

### ISSUE THREAD

**Issue by mehti1367** [FreedomPrevails/JSMTProxy#27]
cant start JSM On Windows, proof:

https://uptostream.com/8edfmucvojfr

**Comment by PayamSoft** [comment]
I have same problem. log show as below.

0|mtproxy  | Error: bind EADDRINUSE null:5478
0|mtproxy  |     at Object._errnoException (util.js:992:11)
0|mtproxy  |     at _exceptionWithHostPort (util.js:1014:20)
0|mtproxy  |     at listenOnMasterHandle (net.js:1415:16)
0|mtproxy  |     at shared (internal/cluster/child.js:115:3)
0|mtproxy  |     at Worker.send (internal/cluster/child.js:86:7)
0|mtproxy  |     at process.onInternalMessage (internal/cluster/utils.js:42:8)
0|mtproxy  |     at emitTwo (events.js:131:20)
0|mtproxy  |     at process.emit (events.js:214:7)
0|mtproxy  |     at emit (internal/child_process.js:772:12)
0|mtproxy  |     at _combinedTickCallback (internal/process/next_tick.js:141:11)

**Comment by PayamSoft** [comment]
0|mtproxy  |     at emitTwo (events.js:131:20)
0|mtproxy  |     at process.emit (events.js:214:7)
0|mtproxy  |     at emit (internal/child_process.js:772:12)
0|mtproxy  |     at _combinedTickCallback (internal/process/next_tick.js:141:11)

0|mtproxy  | Error: bind EADDRINUSE null:5478
0|mtproxy  |     at Object._errnoException (util.js:992:11)
0|mtproxy  |     at _exceptionWithHostPort (util.js:1014:20)
0|mtproxy  |     at listenOnMasterHandle (net.js:1415:16)
0|mtproxy  |     at shared (internal/cluster/child.js:115:3)
0|mtproxy  |     at Worker.send (internal/cluster/child.js:86:7)
0|mtproxy  |     at process.onInternalMessage (internal/cluster/utils.js:42:8)
0|mtproxy  |     at emitTwo (events.js:131:20)
0|mtproxy  |     at process.emit (events.js:214:7)
0|mtproxy  |     at emit (internal/child_process.js:772:12)
0|mtproxy  |     at _combinedTickCallback (internal/process/next_tick.js:141:11)

**Comment by mehti1367** [comment]
I found the problem , we have to change port and secret.

**Comment by VahidN** [comment]
More info in Persian: https://paskoocheh.com/blog/posts/2018-07-31-bgp-hijack-telegram-iran.html
In English: https://bgpstream.com/event/144057
