### ISSUE TITLE
dont run on ubuntu

### ISSUE THREAD

**Issue by karimi12** [FreedomPrevails/JSMTProxy#33]
i do manual step by step 
an then get this error 

`
PM2        | Error: ENOENT: no such file or directory, uv_cwd
PM2        |     at Object.resolve (path.js:1077:24)
PM2        |     at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:480:17)
PM2        |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:575:20)
PM2        |     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
PM2        |     at Module.require (internal/modules/cjs/loader.js:637:17)
PM2        |     at require (internal/modules/cjs/helpers.js:22:18)
PM2        |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:13:15)
PM2        |     at Module._compile (internal/modules/cjs/loader.js:701:30)
PM2        |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
PM2        |     at Module.load (internal/modules/cjs/loader.js:600:32)
PM2        | 2019-05-18T16:10:54: PM2 log: App name:mtproxy id:1 disconnected
PM2        | 2019-05-18T16:10:54: PM2 log: App [mtproxy:1] exited with code [1] via signal [SIGINT]
PM2        | 2019-05-18T16:10:54: PM2 log: Script /root/JSMTProxy/mtproxy.js had too many unstable restarts (16). Stopped. "errored"
PM2        | 2019-05-18T16:10:54: PM2 error: Cancelling versioning data parsing`

**Comment by alikhosronejad** [comment]
use 

> cd JSMTProxy

 and next use 

> pm2 start mtproxy.js -i max
