### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by p1ratrulezzz** [FreedomPrevails/JSMTProxy#9]
```

1|mtproxy  | SHORT ON IDLE SERVER CONNECTIONS! dcId: 4
1|mtproxy  | SHORT ON IDLE SERVER CONNECTIONS! dcId: 4
1|mtproxy  | SHORT ON IDLE SERVER CONNECTIONS! dcId: 4
1|mtproxy  | SHORT ON IDLE SERVER CONNECTIONS! dcId: 4
1|mtproxy  | SHORT ON IDLE SERVER CONNECTIONS! dcId: 4
1|mtproxy  | SHORT ON IDLE SERVER CONNECTIONS! dcId: 4
1|mtproxy  | SHORT ON IDLE SERVER CONNECTIONS! dcId: 4
1|mtproxy  | SHORT ON IDLE SERVER CONNECTIONS! dcId: 4
1|mtproxy  | SHORT ON IDLE SERVER CONNECTIONS! dcId: 4
1|mtproxy  | SHORT ON IDLE SERVER CONNECTIONS! dcId: 4
1|mtproxy  | SHORT ON IDLE SERVER CONNECTIONS! dcId: 4
1|mtproxy  | SHORT ON IDLE SERVER CONNECTIONS! dcId: 4
```

Also have

```
TypeError: Cannot read property 'substr' of undefined
    at Socket.<anonymous> (/opt/JSMTProxy/mtproxy.js:158:41)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

I have these errors in logs and even if I have only 1 connected client - cpu load is near 60%

OS: Ubuntu 18.04
NodeJS: v8.11.2
pm2: 2.10.4

```
Connections per second: 70 DC1: 7 DC2: 13 DC3: 1 DC4: 48 DC5: 2
Connections per second: 58 DC1: 2 DC2: 8 DC3: 1 DC4: 48 DC5: 0
Connections per second: 57 DC1: 2 DC2: 7 DC3: 1 DC4: 48 DC5: 1
Connections per second: 58 DC1: 2 DC2: 7 DC3: 1 DC4: 48 DC5: 1
Connections per second: 55 DC1: 2 DC2: 6 DC3: 0 DC4: 48 DC5: 1
Connections per second: 59 DC1: 2 DC2: 8 DC3: 1 DC4: 49 DC5: 1
Connections per second: 59 DC1: 2 DC2: 8 DC3: 1 DC4: 49 DC5: 1
Connections per second: 54 DC1: 1 DC2: 7 DC3: 1 DC4: 46 DC5: 0
Connections per second: 55 DC1: 2 DC2: 7 DC3: 1 DC4: 46 DC5: 1
Connections per second: 58 DC1: 2 DC2: 8 DC3: 1 DC4: 47 DC5: 2
Connections per second: 56 DC1: 4 DC2: 7 DC3: 0 DC4: 46 DC5: 1
Connections per second: 57 DC1: 2 DC2: 8 DC3: 1 DC4: 47 DC5: 1
```

So looks like somehow there is some DDOS on this server. Is there any way to queue connections and etc to protect from very often requests?

UPD: 
With 
netstat -ntu | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -n

I checked which IPs are ddosing port 6969. So for some reason they are telegram DC servers!
```
   229: 149.154.167.51
   2297: 149.154.167.91
```

**Comment by svegan** [comment]
Same here =/

**Comment by YaSoC** [comment]
Did anyone find a way to solve it ?
